{
 "title": "CodeProm Health (Prod)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{handler}} - {{status}}" }
   ]
  },
  {
   "title": "Order Errors (Failure Simulation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "Errors ({{handler}})"
    }
   ]
  },
  {
   "title": "API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}} - Average Latency"
    }
   ]
  },
  {
   "title": "Service CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "Backend CPU Usage" }
   ]
  }
 ]
}